### ISSUE TITLE
What is it good for?

### ISSUE THREAD

**Issue by MartinThoma** [gbm-bailleul/padaf#9]
Hello,

Could you please extend the README? What is this repository about? What are requisites to install it?

Best regards,
Martin

**Comment by eric-gc** [comment]
Hi,

I have no rights on this repo but here is a quick answer :)

Padaf validates PDF files against the PDF/A-1b standard.
This project has been integrated to Apache PDFBox under the name
"Preflight".
See the Apache PDFBox website for more details :
- https://pdfbox.apache.org
- https://pdfbox.apache.org/1.8/cookbook/pdfavalidation.html

Regards,
Eric

2015-06-14 10:46 GMT+02:00 Martin Thoma notifications@github.com:

**Comment by gbm-bailleul** [comment]
Thanks Eric for this help.

Had very few time these last months
